### PR TITLE
Dev: "Finished" schematic and layout for 1_Interface_Charge_RBF board

### PR DESCRIPTION
**Pull request by YanAzer**
Waiting further reviews for generating fabrication files for the first board of the interface board project.

### CODE REVIEW

**Comment by mgm8** [comment]
@YanAzer can you export a PDF file with the schematic and the PCB layout?

**Comment by mgm8** [comment]
@YanAzer also, remove the RoHS symbol from the silkscreen layer. PCBs for space applications are not RoHS compliant.

**Comment by YanAzer** [comment]
Just ignore the commit 3c8f2587725d1ac3b1bd4feefa77be8d73c3c0e7, i forgot that new commits are added to the already opened pull request.

**Review by mgm8 — CHANGES_REQUESTED** [review]
The pins of the PicoBlades connectors are inverted! The PicoCable cables from Molex invert the signals as can be seen in the datasheet: [https://www.molex.com/pdm_docs/sd/151340601_sd.pdf](https://www.molex.com/pdm_docs/sd/151340601_sd.pdf)

Example:

JTAG connector of the OBDH (FloripaSat-I):
obdh_fm_fsat

Interface board of the FloripaSat-I
if_fm_fsat
if_fsat-3d

New interface board:
if_golds
3d_if_golds

**Comment by YanAzer** [comment]
@mgm8 can you please see the changes made? I made a multiboard view with EPS 2.0 to be more clear about the pin connections (see the image below)
connectors-pin-check-IIPN1

**Review by mgm8 — APPROVED** [review]

**Pull request merged**
